export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const VISIT_RESTAURANT = 'VISIT_RESTAURANT';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_VISITED: 'SHOW_VISITED',
  SHOW_PENDING: 'SHOW_PENDING'
};
